
import { getKindeServerSession} from '@kinde-oss/kinde-auth-nextjs/server';
import NavBar from '../components/NavBar'
import './globals.css'
import { Nunito_Sans } from 'next/font/google'


const nunNunito_Sans = Nunito_Sans({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}) {
  const {isAuthenticated, getUser} = getKindeServerSession();
  const auth = isAuthenticated();
  const user = getUser();
  return (
    <html lang="en">   
      <body className={`${nunNunito_Sans.className} bg-slate-950 tracking-wide` }>
       
        <NavBar 
          auth={auth}
          user={user}/>
        {children}
        
        </body>    
    </html>
  )
}
