import NavBar from "../components/NavBar";
import { AuthPageProvider } from "../context/authContext";
import { SearchProvider } from "../context/searchContext";
import { WatchlistProvider } from "../context/watchListContext";
import "./globals.css";
import { Nunito_Sans } from "next/font/google";

const nunNunito_Sans = Nunito_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${nunNunito_Sans.className} bg-prussianBlueDeep tracking-wide min-h-screen`}
      >
        <AuthPageProvider>
          <SearchProvider>
            <NavBar />
            <WatchlistProvider>{children}</WatchlistProvider>
          </SearchProvider>
        </AuthPageProvider>
      </body>
    </html>
  );
}
